from pathlib import Path

RASPBERRY_ROOT = Path(__file__).resolve().parent
MODEL_PATH = RASPBERRY_ROOT / "model" / "best.pt"

DEFAULT_DEVICE = "raspberry"
DEFAULT_CAMERA_INDEX = 0
DEFAULT_IMGSZ = 224
DEFAULT_CONF = 0.85
DEFAULT_FRAME_INTERVAL = 0.05
REJECT_COOLDOWN_SEC = 2.0

# Kamera thread
CAMERA_SCAN_INTERVAL_SEC = 1.0
CAMERA_READ_FAIL_MAX = 15
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
USB_CAMERA_SCAN_MAX_INDEX = 6
PREVIEW_WINDOW_NAME = "Bottle Inspection"

# Arduino over USB serial
ARDUINO_MODE = "mock"
DEFAULT_SERIAL_PORT = "/dev/ttyACM0"
DEFAULT_BAUD_RATE = 115200
ARDUINO_REJECT_CMD = "REJECT\n"
