from pathlib import Path

RASPBERRY_ROOT = Path(__file__).resolve().parent
MODEL_PATH = RASPBERRY_ROOT / "model" / "best.pt"

DEFAULT_DEVICE = "raspberry"
DEFAULT_CAMERA_INDEX = 0
DEFAULT_IMGSZ = 224
DEFAULT_CONF = 0.85
DEFAULT_FRAME_INTERVAL = 0.05
REJECT_COOLDOWN_SEC = 2.0

# Kamera thread
CAMERA_SCAN_INTERVAL_SEC = 1.0
CAMERA_READ_FAIL_MAX = 15
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
USB_CAMERA_SCAN_MAX_INDEX = 6
PREVIEW_WINDOW_NAME = "Bottle Inspection"

# Asama 1: sise tespiti (COCO bottle) — sise yoksa accept/reject yapma
BOTTLE_DETECT_MODEL = "yolov8n.pt"
BOTTLE_DETECT_CONF = 0.45
COCO_BOTTLE_CLASS_ID = 39
BOTTLE_CROP_PADDING = 0.05

# Onizleme cerceve kalinligi (BGR)
FRAME_BORDER_THICKNESS = 6
COLOR_ACCEPT_BGR = (0, 255, 0)
COLOR_REJECT_BGR = (0, 0, 255)
COLOR_NO_BOTTLE_BGR = (0, 200, 255)

# Arduino over USB serial
ARDUINO_MODE = "mock"
DEFAULT_SERIAL_PORT = "/dev/ttyACM0"
DEFAULT_BAUD_RATE = 115200
ARDUINO_REJECT_CMD = "REJECT\n"
